schema:
  name: "dbo"

spring:
  data:
    rest:
      default-page-size= 20
      max-page-size= 1000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${schema.name}
  datasource:
    url: jdbc:sqlserver://localhost:1433;user=sa;password=SuperP4ssw0rd!
  flyway:
    schemas: ${schema.name}
    default-schema: ${schema.name}
    locations: classpath:db/migration/sqlServer, classpath:db/migration/sqlServer-data
    table: flyway_history